### ISSUE TITLE
Can no longer fetch tickets 

### ISSUE THREAD

**Issue by morkeleb** [caged/lighthouse-api#15]
I have a small program that once a week checks how many tickets we have in different buckets.
Since a few weeks ago I can no longer fetch the tickets from the api.

I get the following error
rake aborted!
LoadError: cannot load such file -- active_support/core_ext/module/attr_accessor_with_default

The callback says its from the tag.rb file.

I can't figure out what changed, it seems nothing in the api changed.
Is there a breaking change on the web side?

**Comment by erictheise** [comment]
What timing, @morkeleb! I just started trying to use this gem today and was puzzling over the same error, wondering how long it'd been a problem since there haven't been any updates since 2010.

**Comment by erictheise** [comment]
Hmmm, well, despite [what one set of docs seems to say](http://guides.rubyonrails.org/v3.2.21/active_support_core_extensions.html#attr_accessor_with_default), [another](http://apidock.com/rails/v3.1.0/Module/attr_accessor_with_default) says that `attr_accessor_with_default` was removed in Rails 3.2.

**Comment by morkeleb** [comment]
Did you figure out a fix?

**Comment by erictheise** [comment]
My needs are simple (advancing ticket statuses after deploying to staging or production servers), so after digging down a couple of layers on this issue, I ended up hitting the Lighthouse API directly using `curb`.

**Comment by courtenay** [comment]
This repo is not maintained, caged doesn't work on lighthouse - try our company repo instead, which has a fix for this https://github.com/entp/lighthouse-api

**Comment by morkeleb** [comment]
Great! Ill try that out, you might want to look into contacting ruby gems to changed the published gem.
Also update their webpage link to link to your repo.

**Comment by morkeleb** [comment]
I've tried changing the ruby lighthouse-api gem to the maintained.
That changes the error I get but I still can't fetch tickets from the api.
i tried using activeresource 4.0 as specified in your gem as well as the 3.0 version that "used to work".

The error is included below, your github fork does not allow raising of issues.

rake aborted!

ArgumentError: expected an attributes Hash, got "2"

/Users/morten/src/remotex/reportsender/Statismix/ruby/2.0.0/gems/activeresource-3.0.0/lib/active_resource/base.rb:1217:in `load'

/Users/morten/src/remotex/reportsender/Statismix/ruby/2.0.0/gems/activeresource-3.0.0/lib/active_resource/base.rb:965:in `initialize'

/Users/morten/src/remotex/reportsender/Statismix/ruby/2.0.0/gems/activeresource-3.0.0/lib/active_resource/base.rb:889:in `new'

/Users/morten/src/remotex/reportsender/Statismix/ruby/2.0.0/gems/activeresource-3.0.0/lib/active_resource/base.rb:889:in `instantiate_record'

/Users/morten/src/remotex/reportsender/Statismix/ruby/2.0.0/gems/activeresource-3.0.0/lib/active_resource/base.rb:885:in `block in instantiate_collection'

/Users/morten/src/remotex/reportsender/Statismix/ruby/2.0.0/gems/activeresource-3.0.0/lib/active_resource/base.rb:885:in `collect!'

/Users/morten/src/remotex/reportsender/Statismix/ruby/2.0.0/gems/activeresource-3.0.0/lib/active_resource/base.rb:885:in `instantiate_collection'

/Users/morten/src/remotex/reportsender/Statismix/ruby/2.0.0/gems/activeresource-3.0.0/lib/active_resource/base.rb:857:in `find_every'

/Users/morten/src/remotex/reportsender/Statismix/ruby/2.0.0/gems/activeresource-3.0.0/lib/active_resource/base.rb:777:in `find'

/Users/morten/src/remotex/reportsender/Statismix/ruby/2.0.0/bundler/gems/lighthouse-api-7b7239bdb25c/lib/lighthouse/project.rb:47:in `tickets'

**Comment by morkeleb** [comment]
The error seems to come from activeresource trying to remove the root: https://github.com/rails/activeresource/issues/86

The monkey patch in the issue I linked doesn't solve the issue.
