### ISSUE TITLE
Regression: Crash when creating a ticket through API using a tag

### ISSUE THREAD

**Issue by svetlana** [caged/lighthouse-api#9]
Hello,

I just ran into this trying to create tickets using tags - this used to work in the previous version of the gem.

API call:

Lighthouse::Ticket.create(:project_id => <some integer>, 
                                     :title => "Fake",
                                     :state => "pending",
                                     :tag => "fake,",
                                     :assigned_user_id => <some integer>)

Stack Trace:

NoMethodError: undefined method `returning' for #<Lighthouse::Ticket:0x105c7a9d8>
    from /opt/local/lib/ruby/gems/1.8/gems/activeresource-3.0.7/lib/active_resource/base.rb:1401:in`method_missing'
    from /opt/local/lib/ruby/gems/1.8/gems/lighthouse-api-2.0/lib/lighthouse/ticket.rb:84:in `cleanup_tags'
    from /opt/local/lib/ruby/gems/1.8/gems/lighthouse-api-2.0/lib/lighthouse/ticket.rb:80:in`parse_with_spaces'
    from /opt/local/lib/ruby/gems/1.8/gems/lighthouse-api-2.0/lib/lighthouse/ticket.rb:38:in `tags'
    from /opt/local/lib/ruby/gems/1.8/gems/lighthouse-api-2.0/lib/lighthouse/ticket.rb:60:in`save'
    from /opt/local/lib/ruby/gems/1.8/gems/activeresource-3.0.7/lib/active_resource/base.rb:710:in `create'
    from /opt/local/lib/ruby/gems/1.8/gems/activeresource-3.0.7/lib/active_resource/base.rb:710:in`tap'
    from /opt/local/lib/ruby/gems/1.8/gems/activeresource-3.0.7/lib/active_resource/base.rb:710:in `create'
    from (irb):175
    from :0

This is blocking me from creating tickets, which I have to do asap. Please help? :)

**Comment by svetlana** [comment]
Ok, I see what this issue is about - I'm not tracking Lighthouse-api github HEAD. I just currently have lighthouse-api-2.0 (which I re-installed today hoping that the gem was updated). I guess I have a workaround right now, but it is an awesome one. Could you please either rebuild the gem or bump it (bumping it is better).

This is the commit that I'm seeing was made in october of 2010, and since the gem was not bumped / rebuilt: https://github.com/Caged/lighthouse-api/commit/0ae43108a273b865b276e8d9b9cca617a72951ad

It's been a while - would you be able to fix it some time soon please? It is not that hard, is it? Please please?

**Comment by svetlana** [comment]
I fixed the issue on my end by modifying the gem locally, but I think it'd be cool if bumped the gem :)
